travis:
  secure:
    BINSTAR_TOKEN: HU52peB3rUgtXLTMA1M+Quib/SJgYx7acXMrSYRw5tzteHdbGOk0nkeTY7zNnjmH2idZL9EZFekcrVoLbjl/X+3OSaPheP+QCWk88JjMfyhIDd/Nc4apzMz+JAgMAIgZJYtzqOnQqfxHVP8NHTBOBPr5FNrMPe3XfoPNdiBN3KPjKzYSiFTQJGuWdiB7gD0/JGdMICemZUmmhwxYIMtw6T1DMFtyB6DYmy56o8/0tHq+QEY2OCjGFoWl/bntyOnqtRsWMezWDHYiVrEO4WOepVCpKlbKS5OyQ9eqqyLMBapfbRKf4WZwiaQf6PwJNdusK4vdpoYiXG/Br0BkcLooWGroDDGbzt3iIVKl4l+hfI+HrVSKLxJ7clqLOYNZ3Ri37TBMDpxoa4qRh/Rrgvu2mL90WzWiVTQBfPGNiZDinJsOU8d+vT4JN3KZKo+QZ4numO9/2Ahkc1HnZbfP65zh4t/hauJIQvSiMmlp3G6VSba3Q19DFboxdwxkiTIY7AK+KV+85uGCDLaoNmYaOXi3FhbaLBK4B0UrvlxT6vCoB7mHXedO5XPcEgck32vrpA9gahBdIc6ndqJJ8Me1WYXHRK/kdWk6s78/RDntJiIDntcOaflKYrqOXYkqhyDQiRQoCcHd+LjT/k6+VllfGYIqKhJiv8YLhVCKjMoJjzXviRM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
